name: Evaluacion Masiva Manual

on:
  workflow_dispatch:

jobs:
  evaluar:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Instalar GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Instalar dependencias Python
        run: pip install requests

      - name: Ejecutar evaluacion
        env:
          GH_TOKEN: ${{ secrets.ORG_PAT  }}
          RESPUESTAS_JSON: ${{ secrets.RESPUESTAS_JSON }}
          ALUMNOS_CSV: ${{ secrets.ALUMNOS_CSV }}
        run: python scripts/evaluar_masivo.py

      - name: Subir resumen
        uses: actions/upload-artifact@v4
        with:
          name: resumen-evaluacion
          path: resumen_final.csv